config/routes.rb
Astrochimp::Application.routes.draw do
  resources :signups

  root :to => 'signups#new'

end

app/models/config.rb
class Config < Settingslogic
  source "#{Rails.root}/config/astrochimp.yml"
  namespace Rails.env
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/astrochimp.yml"
  namespace Rails.env
end

app/models/signup.rb
class Signup < ActiveRecord::Base
  # Constants
  STATUS_NEW = 0
  STATUS_SUBSCRIBED = 1
  STATUS_INVITED = 2

  # Validations
  validates :email, presence: true, email: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  # GET /signups
  # GET /signups.json
  def index
    redirect_to root_url

    # @signups = Signup.all

    # respond_to do |format|
    #   # format.html # index.html.erb
    #   format.html { render text: 'No list yet :)' }
    #   format.json { render json: @signups }
    # end
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    redirect_to root_url

    # @signup = Signup.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   # format.json { render json: @signup }
    # end
  end

  # GET /signups/new
  # GET /signups/new.json
  def new
    @signup = Signup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signup }
    end
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(params[:signup])
    @signup.status = Signup::STATUS_NEW

    respond_to do |format|
      if @signup.save

        # Handle any MailChimp errors
        begin
          h = Hominid::API.new(Settings.mailchimp.api_key, {:secure => true, :timeout => 60})
          h.list_subscribe(Settings.mailchimp.list_id, @signup.email, {}, Settings.mailchimp.email_format, Settings.mailchimp.email_double_optin)
        rescue Hominid::APIError => e
          @signup.delete # Don't save the record on error - it wasn't subscribed to the MailChimp list
          @signup.errors.add(:email, 'MailChimp API Error: ' + e.message)
        end
      end

      if @signup.errors.any?
        format.html { render action: "new" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      else
        @signup.update_attribute(:status, Signup::STATUS_SUBSCRIBED)

        format.html { redirect_to root_url, notice: Settings.app.signup_success_notice }
        format.json { render json: @signup, status: :created, location: @signup }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Settings.app.name %></title>
  <%= stylesheet_link_tag "application" %>
  <link href="http://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet" type="text/css" />
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <!-- Content -->
    <div class="row">
      <div class="span12">
        <div class="hero-unit">
          <h2>Kinsai by Jason Doo</h2>
            <div id="logo">
              <%= image_tag('persimmon.png') %>
            </div>
          <h2>Coming Soon</h2>
          <p id="inquiries">Please <a href="mailto:doojason@gmail.com">email us</a> with any inquiries</p>
        </div>
          <div id="signup_box">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
      </div>
    </div>
  </div>
  <!-- JavaScripts -->
  <% if !Settings.app.google_analytics_code.blank? -%>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= Settings.app.google_analytics_code %>']);
    _gaq.push(['_trackPageview']);

    (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <% end %>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <div class="span6 center">
    <% if @signup.errors.any? %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <% @signup.errors.full_messages.each do |msg| %>
          <%= content_tag :div, msg, :id => "flash_error" if msg.is_a?(String) %>
        <% end %>
      </div>
    <% end %>

    <div class="control-group">
      <div class="controls">
        <div class="input-append"> 
          <%= text_field_tag :email, (params[:signup][:email] if params[:signup] or nil), name: 'signup[email]', placeholder: 'Leave your email for occasional updates.', class: 'span4 btn-large' %>
          <%= submit_tag 'Submit &raquo;'.html_safe, class: 'btn btn-success btn-large', id: 'submit' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signups.each do |signup| %>
  <tr>
    <td><%= link_to 'Show', signup %></td>
    <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
    <td><%= link_to 'Destroy', signup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signup', new_signup_path %>

app/views/signups/new.html.erb
<%= render 'form' %>

app/views/signups/show.html.erb
<p>Not yet!</p>